pub fn i_can_throw_two() -> Result<(), u32> {
    Err(32)
}
